
import './globals.css'
import { Inter } from 'next/font/google'
import { SocialIcon } from 'react-social-icons'
import Link from 'next/link'
import Footer from '@/components/footer'
import Navbar from '@/components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'InDeADS',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='Container'>  
            <div className='item Navbar'> <Navbar/> </div>   
            <div className='item Column'> 
                <div className='flexContainer'>
                    <div className='flexContent' ><button className='button'><Link href='/business' className='pagelink'> Business </Link></button></div>
                    <div className='flexContent' ><button className='button'><Link href='/contact' className='pagelink'> Contact </Link></button></div>
                    <div className='flexContent' ><button className='button'><Link href='/report' className='pagelink'> Report </Link></button></div>
                    <div className='flexContent' ><button className='button'><Link href='/business' className='pagelink'> Example </Link></button></div>
                    <div className='flexContent' ><button className='button'><Link href='/business' className='pagelink'> Example </Link></button></div>
                </div>
            </div>
            <div className='item mainbody'>
              {children}
            </div>
            <div className='item Footer'> <Footer/> </div>
        </div>
      
      </body>
    </html>
  )
}
